
// This file has been generated by the GUI designer. Do not modify.
namespace Osobni_Troškovnik
{
	public partial class BarWindow
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Osobni_Troškovnik.BarWindow
			this.Name = "Osobni_Troškovnik.BarWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("BarWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.KeyPress);
		}
	}
}
