
// This file has been generated by the GUI designer. Do not modify.
namespace Osobni_Troškovnik
{
	public partial class NovaKategorijaWidow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Entry novaKategorija;

		private global::Gtk.Button spremi;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Osobni_Troškovnik.NovaKategorijaWidow
			this.WidthRequest = 300;
			this.HeightRequest = 100;
			this.Name = "Osobni_Troškovnik.NovaKategorijaWidow";
			this.Title = global::Mono.Unix.Catalog.GetString("NovaKategorijaWidow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.BorderWidth = ((uint)(15));
			this.Resizable = false;
			// Container child Osobni_Troškovnik.NovaKategorijaWidow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Homogeneous = true;
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.novaKategorija = new global::Gtk.Entry();
			global::Gtk.Tooltips w1 = new Gtk.Tooltips();
			w1.SetTip(this.novaKategorija, "Naziv nove kategorije, do 20 znakova", "Naziv nove kategorije, do 20 znakova");
			this.novaKategorija.CanFocus = true;
			this.novaKategorija.Name = "novaKategorija";
			this.novaKategorija.IsEditable = true;
			this.novaKategorija.InvisibleChar = '●';
			this.vbox1.Add(this.novaKategorija);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.novaKategorija]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(15));
			// Container child vbox1.Gtk.Box+BoxChild
			this.spremi = new global::Gtk.Button();
			this.spremi.CanFocus = true;
			this.spremi.Name = "spremi";
			this.spremi.UseUnderline = true;
			this.spremi.Label = global::Mono.Unix.Catalog.GetString("Spremi");
			this.vbox1.Add(this.spremi);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.spremi]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 353;
			this.DefaultHeight = 150;
			this.Show();
			this.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.KeyPress);
			this.spremi.Clicked += new global::System.EventHandler(this.spremiKategorijuClicked);
		}
	}
}
