
// This file has been generated by the GUI designer. Do not modify.
namespace Osobni_Troškovnik
{
	public partial class DatumChooseWindow
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label3;

		private global::Gtk.Label label4;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Calendar kalendarOd;

		private global::Gtk.Calendar kalendarDo;

		private global::Gtk.Button filtrirajButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Osobni_Troškovnik.DatumChooseWindow
			this.Name = "Osobni_Troškovnik.DatumChooseWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("DatumChooseWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(6));
			this.Resizable = false;
			// Container child Osobni_Troškovnik.DatumChooseWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Početak");
			this.hbox1.Add(this.label3);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label3]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Kraj");
			this.hbox1.Add(this.label4);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label4]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Homogeneous = true;
			this.hbox3.Spacing = 20;
			// Container child hbox3.Gtk.Box+BoxChild
			this.kalendarOd = new global::Gtk.Calendar();
			this.kalendarOd.CanFocus = true;
			this.kalendarOd.Name = "kalendarOd";
			this.kalendarOd.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.hbox3.Add(this.kalendarOd);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.kalendarOd]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.kalendarDo = new global::Gtk.Calendar();
			this.kalendarDo.CanFocus = true;
			this.kalendarDo.Name = "kalendarDo";
			this.kalendarDo.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.hbox3.Add(this.kalendarDo);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.kalendarDo]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox2.Add(this.hbox3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.filtrirajButton = new global::Gtk.Button();
			this.filtrirajButton.CanFocus = true;
			this.filtrirajButton.Name = "filtrirajButton";
			this.filtrirajButton.UseUnderline = true;
			this.filtrirajButton.Label = global::Mono.Unix.Catalog.GetString("Filtriraj");
			this.vbox2.Add(this.filtrirajButton);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.filtrirajButton]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 458;
			this.DefaultHeight = 277;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.onDeleteEvent);
			this.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.KeyPress);
			this.filtrirajButton.Clicked += new global::System.EventHandler(this.filtrirajClicked);
		}
	}
}
