
// This file has been generated by the GUI designer. Do not modify.
namespace Osobni_Troškovnik
{
	public partial class MainWindow
	{
		private global::Gtk.Notebook notebook;

		private global::Gtk.EventBox eventboxHome;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Image image1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.Button button2;

		private global::Gtk.Button button1;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Fixed fixed4;

		private global::Gtk.Button button3;

		private global::Gtk.Button button4;

		private global::Gtk.Fixed fixed3;

		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Button button5;

		private global::Gtk.Label label1;

		private global::Gtk.EventBox eventBoxTroskovi;

		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Button backButton;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Fixed fixed6;

		private global::Gtk.Fixed fixed11;

		private global::Gtk.Button button7;

		private global::Gtk.HBox hbox14;

		private global::Gtk.Label datumLabel;

		private global::Gtk.Fixed fixed12;

		private global::Gtk.Button button8;

		private global::Gtk.HBox hbox4;

		private global::Gtk.ScrolledWindow kategorijeSW;

		private global::Gtk.HBox kategorijeHBox;

		private global::Gtk.VBox vbox6;

		private global::Gtk.HBox hbox5;

		private global::Gtk.ScrolledWindow scrolledwindow2;

		private global::Gtk.NodeView nodeView;

		private global::Gtk.VBox vbox7;

		private global::Gtk.HBox hbox15;

		private global::Gtk.VBox vbox15;

		private global::Gtk.Label label10;

		private global::Gtk.Label label2;

		private global::Gtk.Label label4;

		private global::Gtk.VBox vbox16;

		private global::Gtk.Label kategorijaLabel;

		private global::Gtk.Label infoUkupno;

		private global::Gtk.Label infoProsjek;

		private global::Gtk.VBox vbox14;

		private global::Gtk.Label label6;

		private global::Gtk.HBox hbox6;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView opisView;

		private global::Gtk.Button editButton;

		private global::Gtk.EventBox eventBoxTotalTroskovi;

		private global::Gtk.Table table1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView treeView;

		private global::Gtk.HBox hbox12;

		private global::Gtk.Button backButton1;

		private global::Gtk.HBox hbox17;

		private global::Gtk.Fixed fixed13;

		private global::Gtk.Button button9;

		private global::Gtk.Label datumLabela1;

		private global::Gtk.Button button10;

		private global::Gtk.HBox hbox13;

		private global::Gtk.HBox hbox26;

		private global::Gtk.Label label25;

		private global::Gtk.Label labelaUkupno;

		private global::Gtk.HBox hbox29;

		private global::Gtk.Label label23;

		private global::Gtk.Label labelaPrekoračeno;

		private global::Gtk.HBox hbox30;

		private global::Gtk.Label label16;

		private global::Gtk.Label labelBudzet;

		private global::Gtk.HBox hbox16;

		private global::Gtk.HBox hbox27;

		private global::Gtk.Label label21;

		private global::Gtk.Label labelaKategorija;

		private global::Gtk.HBox hbox28;

		private global::Gtk.Label label19;

		private global::Gtk.Label labelaTrosakKategorije;

		private global::Gtk.ProgressBar progressbarBudget;

		private global::Gtk.ProgressBar progressbarUdio;

		private global::Gtk.Label label3;

		private global::Gtk.EventBox eventBoxStatistika;

		private global::Gtk.VBox statMainVBox;

		private global::Gtk.VBox vbox9;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Button button11;

		private global::Gtk.Fixed fixed5;

		private global::Gtk.HBox hbox23;

		private global::Gtk.Button button12;

		private global::Gtk.Label datumLabela;

		private global::Gtk.HBox hbox25;

		private global::Gtk.Fixed fixed10;

		private global::Gtk.Button button6;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Label label12;

		private global::Gtk.HBox hbox21;

		private global::Gtk.Label label13;

		private global::Gtk.ComboBox kategorijeCombo;

		private global::Gtk.HBox hbox22;

		private global::Gtk.Fixed fixed9;

		private global::Gtk.HBox hbox24;

		private global::Gtk.Label label14;

		private global::Gtk.SpinButton odabranaGodina;

		private global::Gtk.HBox hbox11;

		private global::Gtk.HBox hbox18;

		private global::Gtk.Button totalBar;

		private global::Gtk.Button totalPie;

		private global::Gtk.Button totalLine;

		private global::Gtk.HBox hbox20;

		private global::Gtk.Fixed fixed7;

		private global::Gtk.Button kategorijaBar;

		private global::Gtk.Button kategorijaLine;

		private global::Gtk.HBox hbox19;

		private global::Gtk.Fixed fixed8;

		private global::Gtk.Button prikazPoBar;

		private global::Gtk.Button prikazPoPie;

		private global::Gtk.VBox plotBox;

		private global::Gtk.Label label5;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Osobni_Troškovnik.MainWindow
			this.Name = "Osobni_Troškovnik.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DefaultWidth = 700;
			this.DefaultHeight = 560;
			// Container child Osobni_Troškovnik.MainWindow.Gtk.Container+ContainerChild
			this.notebook = new global::Gtk.Notebook();
			this.notebook.CanFocus = true;
			this.notebook.Name = "notebook";
			this.notebook.CurrentPage = 3;
			this.notebook.ShowBorder = false;
			this.notebook.ShowTabs = false;
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.eventboxHome = new global::Gtk.EventBox();
			this.eventboxHome.Name = "eventboxHome";
			// Container child eventboxHome.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.image.png");
			this.vbox1.Add(this.image1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.image1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 20;
			this.hbox1.BorderWidth = ((uint)(10));
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.hbox1.Add(this.fixed2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.fixed2]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.dodajTrosak.png");
			this.button2.Image = w3;
			this.hbox1.Add(this.button2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button2]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			global::Gtk.Image w5 = new global::Gtk.Image();
			w5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.popisTroskova.png");
			this.button1.Image = w5;
			this.hbox1.Add(this.button1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button1]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox1.Add(this.fixed1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.fixed1]));
			w7.Position = 3;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 20;
			// Container child hbox2.Gtk.Box+BoxChild
			this.fixed4 = new global::Gtk.Fixed();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			this.hbox2.Add(this.fixed4);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.fixed4]));
			w9.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			global::Gtk.Image w10 = new global::Gtk.Image();
			w10.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.ukupniTroskovi.png");
			this.button3.Image = w10;
			this.hbox2.Add(this.button3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button3]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button4 = new global::Gtk.Button();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			global::Gtk.Image w12 = new global::Gtk.Image();
			w12.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.statistika.png");
			this.button4.Image = w12;
			this.hbox2.Add(this.button4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button4]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			this.hbox2.Add(this.fixed3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.fixed3]));
			w14.Position = 3;
			this.vbox2.Add(this.hbox2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			this.vbox1.Add(this.vbox4);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox4]));
			w17.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button5 = new global::Gtk.Button();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			global::Gtk.Image w18 = new global::Gtk.Image();
			w18.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.izlaz.png");
			this.button5.Image = w18;
			this.hbox3.Add(this.button5);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button5]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w20.Position = 3;
			w20.Expand = false;
			w20.Fill = false;
			this.eventboxHome.Add(this.vbox1);
			this.notebook.Add(this.eventboxHome);
			// Notebook tab
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("page1");
			this.notebook.SetTabLabel(this.eventboxHome, this.label1);
			this.label1.ShowAll();
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.eventBoxTroskovi = new global::Gtk.EventBox();
			this.eventBoxTroskovi.Name = "eventBoxTroskovi";
			// Container child eventBoxTroskovi.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.backButton = new global::Gtk.Button();
			this.backButton.WidthRequest = 0;
			this.backButton.HeightRequest = 0;
			this.backButton.CanFocus = true;
			this.backButton.Name = "backButton";
			this.backButton.UseUnderline = true;
			global::Gtk.Image w23 = new global::Gtk.Image();
			w23.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.smallBack.png");
			this.backButton.Image = w23;
			this.hbox7.Add(this.backButton);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.backButton]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 55;
			// Container child hbox8.Gtk.Box+BoxChild
			this.fixed6 = new global::Gtk.Fixed();
			this.fixed6.Name = "fixed6";
			this.fixed6.HasWindow = false;
			this.hbox8.Add(this.fixed6);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.fixed6]));
			w25.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.fixed11 = new global::Gtk.Fixed();
			this.fixed11.Name = "fixed11";
			this.fixed11.HasWindow = false;
			this.hbox8.Add(this.fixed11);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.fixed11]));
			w26.Position = 1;
			// Container child hbox8.Gtk.Box+BoxChild
			this.button7 = new global::Gtk.Button();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			global::Gtk.Image w27 = new global::Gtk.Image();
			w27.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.filterDatum.png");
			this.button7.Image = w27;
			this.hbox8.Add(this.button7);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.button7]));
			w28.Position = 2;
			w28.Expand = false;
			w28.Fill = false;
			this.hbox7.Add(this.hbox8);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.hbox8]));
			w29.Position = 1;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.datumLabel = new global::Gtk.Label();
			this.datumLabel.Name = "datumLabel";
			this.datumLabel.Xalign = 0.1F;
			this.hbox14.Add(this.datumLabel);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.datumLabel]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.fixed12 = new global::Gtk.Fixed();
			this.fixed12.Name = "fixed12";
			this.fixed12.HasWindow = false;
			this.hbox14.Add(this.fixed12);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.fixed12]));
			w31.Position = 1;
			// Container child hbox14.Gtk.Box+BoxChild
			this.button8 = new global::Gtk.Button();
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			global::Gtk.Image w32 = new global::Gtk.Image();
			w32.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.brisiSve.png");
			this.button8.Image = w32;
			this.hbox14.Add(this.button8);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.button8]));
			w33.Position = 2;
			w33.Expand = false;
			w33.Fill = false;
			this.hbox7.Add(this.hbox14);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.hbox14]));
			w34.Position = 2;
			this.vbox5.Add(this.hbox7);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox7]));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 15;
			// Container child hbox4.Gtk.Box+BoxChild
			this.kategorijeSW = new global::Gtk.ScrolledWindow();
			this.kategorijeSW.WidthRequest = 300;
			this.kategorijeSW.CanFocus = true;
			this.kategorijeSW.Name = "kategorijeSW";
			this.kategorijeSW.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child kategorijeSW.Gtk.Container+ContainerChild
			global::Gtk.Viewport w36 = new global::Gtk.Viewport();
			w36.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.kategorijeHBox = new global::Gtk.HBox();
			this.kategorijeHBox.Name = "kategorijeHBox";
			this.kategorijeHBox.Spacing = 6;
			w36.Add(this.kategorijeHBox);
			this.kategorijeSW.Add(w36);
			this.hbox4.Add(this.kategorijeSW);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.kategorijeSW]));
			w39.Position = 0;
			w39.Expand = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			this.nodeView = new global::Gtk.NodeView();
			this.nodeView.CanFocus = true;
			this.nodeView.Name = "nodeView";
			this.scrolledwindow2.Add(this.nodeView);
			this.hbox5.Add(this.scrolledwindow2);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.scrolledwindow2]));
			w41.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox();
			this.hbox15.Name = "hbox15";
			this.hbox15.Homogeneous = true;
			this.hbox15.Spacing = 6;
			this.hbox15.BorderWidth = ((uint)(15));
			// Container child hbox15.Gtk.Box+BoxChild
			this.vbox15 = new global::Gtk.VBox();
			this.vbox15.Name = "vbox15";
			this.vbox15.Homogeneous = true;
			this.vbox15.Spacing = 10;
			// Container child vbox15.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.Xalign = 0F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Kategorija: ");
			this.vbox15.Add(this.label10);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.label10]));
			w42.Position = 0;
			w42.Expand = false;
			w42.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Ukupno: ");
			this.vbox15.Add(this.label2);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.label2]));
			w43.Position = 1;
			w43.Expand = false;
			w43.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Prosjek: ");
			this.vbox15.Add(this.label4);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.label4]));
			w44.Position = 2;
			w44.Expand = false;
			w44.Fill = false;
			this.hbox15.Add(this.vbox15);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.vbox15]));
			w45.Position = 0;
			w45.Expand = false;
			w45.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.vbox16 = new global::Gtk.VBox();
			this.vbox16.Name = "vbox16";
			this.vbox16.Homogeneous = true;
			this.vbox16.Spacing = 10;
			// Container child vbox16.Gtk.Box+BoxChild
			this.kategorijaLabel = new global::Gtk.Label();
			this.kategorijaLabel.Name = "kategorijaLabel";
			this.kategorijaLabel.Xalign = 0F;
			this.kategorijaLabel.LabelProp = global::Mono.Unix.Catalog.GetString("-");
			this.vbox16.Add(this.kategorijaLabel);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.kategorijaLabel]));
			w46.Position = 0;
			w46.Expand = false;
			w46.Fill = false;
			// Container child vbox16.Gtk.Box+BoxChild
			this.infoUkupno = new global::Gtk.Label();
			this.infoUkupno.Name = "infoUkupno";
			this.infoUkupno.Xalign = 0F;
			this.vbox16.Add(this.infoUkupno);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.infoUkupno]));
			w47.Position = 1;
			w47.Expand = false;
			w47.Fill = false;
			// Container child vbox16.Gtk.Box+BoxChild
			this.infoProsjek = new global::Gtk.Label();
			this.infoProsjek.Name = "infoProsjek";
			this.infoProsjek.Xalign = 0F;
			this.vbox16.Add(this.infoProsjek);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.infoProsjek]));
			w48.Position = 2;
			w48.Expand = false;
			w48.Fill = false;
			this.hbox15.Add(this.vbox16);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.vbox16]));
			w49.Position = 1;
			w49.Expand = false;
			w49.Fill = false;
			this.vbox7.Add(this.hbox15);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox15]));
			w50.Position = 0;
			w50.Expand = false;
			w50.Fill = false;
			this.hbox5.Add(this.vbox7);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox7]));
			w51.Position = 1;
			w51.Expand = false;
			w51.Fill = false;
			this.vbox6.Add(this.hbox5);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox5]));
			w52.Position = 0;
			// Container child vbox6.Gtk.Box+BoxChild
			this.vbox14 = new global::Gtk.VBox();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			// Container child vbox14.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Opis:");
			this.vbox14.Add(this.label6);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.label6]));
			w53.Position = 0;
			w53.Expand = false;
			w53.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.opisView = new global::Gtk.TextView();
			this.opisView.CanFocus = true;
			this.opisView.Name = "opisView";
			this.opisView.Editable = false;
			this.GtkScrolledWindow.Add(this.opisView);
			this.hbox6.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.GtkScrolledWindow]));
			w55.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.editButton = new global::Gtk.Button();
			this.editButton.HeightRequest = 50;
			this.editButton.CanFocus = true;
			this.editButton.Name = "editButton";
			this.editButton.UseUnderline = true;
			global::Gtk.Image w56 = new global::Gtk.Image();
			w56.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.edit.png");
			this.editButton.Image = w56;
			this.hbox6.Add(this.editButton);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.editButton]));
			w57.Position = 1;
			w57.Expand = false;
			w57.Fill = false;
			this.vbox14.Add(this.hbox6);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.hbox6]));
			w58.Position = 1;
			w58.Expand = false;
			w58.Fill = false;
			this.vbox6.Add(this.vbox14);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.vbox14]));
			w59.Position = 1;
			w59.Expand = false;
			w59.Fill = false;
			this.hbox4.Add(this.vbox6);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox6]));
			w60.Position = 1;
			this.vbox5.Add(this.hbox4);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox4]));
			w61.Position = 1;
			this.eventBoxTroskovi.Add(this.vbox5);
			this.notebook.Add(this.eventBoxTroskovi);
			global::Gtk.Notebook.NotebookChild w63 = ((global::Gtk.Notebook.NotebookChild)(this.notebook[this.eventBoxTroskovi]));
			w63.Position = 1;
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.eventBoxTotalTroskovi = new global::Gtk.EventBox();
			this.eventBoxTotalTroskovi.Name = "eventBoxTotalTroskovi";
			// Container child eventBoxTotalTroskovi.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table(((uint)(7)), ((uint)(1)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(20));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeView = new global::Gtk.TreeView();
			this.treeView.CanFocus = true;
			this.treeView.Name = "treeView";
			this.GtkScrolledWindow1.Add(this.treeView);
			this.table1.Add(this.GtkScrolledWindow1);
			global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.table1[this.GtkScrolledWindow1]));
			w65.TopAttach = ((uint)(1));
			w65.BottomAttach = ((uint)(2));
			w65.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox12 = new global::Gtk.HBox();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.backButton1 = new global::Gtk.Button();
			this.backButton1.WidthRequest = 0;
			this.backButton1.HeightRequest = 0;
			this.backButton1.CanFocus = true;
			this.backButton1.Name = "backButton1";
			this.backButton1.UseUnderline = true;
			global::Gtk.Image w66 = new global::Gtk.Image();
			w66.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.smallBack.png");
			this.backButton1.Image = w66;
			this.hbox12.Add(this.backButton1);
			global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.backButton1]));
			w67.Position = 0;
			w67.Expand = false;
			w67.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.hbox17 = new global::Gtk.HBox();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.fixed13 = new global::Gtk.Fixed();
			this.fixed13.Name = "fixed13";
			this.fixed13.HasWindow = false;
			this.hbox17.Add(this.fixed13);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.fixed13]));
			w68.Position = 0;
			// Container child hbox17.Gtk.Box+BoxChild
			this.button9 = new global::Gtk.Button();
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			this.button9.UseUnderline = true;
			global::Gtk.Image w69 = new global::Gtk.Image();
			w69.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.filterDatum.png");
			this.button9.Image = w69;
			this.hbox17.Add(this.button9);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.button9]));
			w70.Position = 1;
			w70.Expand = false;
			w70.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.datumLabela1 = new global::Gtk.Label();
			this.datumLabela1.Name = "datumLabela1";
			this.datumLabela1.Xalign = 0.15F;
			this.hbox17.Add(this.datumLabela1);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.datumLabela1]));
			w71.Position = 2;
			this.hbox12.Add(this.hbox17);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.hbox17]));
			w72.Position = 1;
			// Container child hbox12.Gtk.Box+BoxChild
			this.button10 = new global::Gtk.Button();
			this.button10.CanFocus = true;
			this.button10.Name = "button10";
			this.button10.UseUnderline = true;
			global::Gtk.Image w73 = new global::Gtk.Image();
			w73.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.budget.png");
			this.button10.Image = w73;
			this.hbox12.Add(this.button10);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.button10]));
			w74.Position = 2;
			w74.Expand = false;
			w74.Fill = false;
			this.table1.Add(this.hbox12);
			global::Gtk.Table.TableChild w75 = ((global::Gtk.Table.TableChild)(this.table1[this.hbox12]));
			w75.XOptions = ((global::Gtk.AttachOptions)(4));
			w75.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox13 = new global::Gtk.HBox();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 130;
			this.hbox13.BorderWidth = ((uint)(6));
			// Container child hbox13.Gtk.Box+BoxChild
			this.hbox26 = new global::Gtk.HBox();
			this.hbox26.Name = "hbox26";
			this.hbox26.Spacing = 6;
			// Container child hbox26.Gtk.Box+BoxChild
			this.label25 = new global::Gtk.Label();
			this.label25.Name = "label25";
			this.label25.Xalign = 0.6F;
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString("Ukupno utrošeno:");
			this.hbox26.Add(this.label25);
			global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.label25]));
			w76.Position = 0;
			w76.Expand = false;
			w76.Fill = false;
			// Container child hbox26.Gtk.Box+BoxChild
			this.labelaUkupno = new global::Gtk.Label();
			this.labelaUkupno.Name = "labelaUkupno";
			this.hbox26.Add(this.labelaUkupno);
			global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.labelaUkupno]));
			w77.Position = 1;
			w77.Fill = false;
			this.hbox13.Add(this.hbox26);
			global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.hbox26]));
			w78.Position = 0;
			w78.Expand = false;
			w78.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.hbox29 = new global::Gtk.HBox();
			this.hbox29.Name = "hbox29";
			this.hbox29.Spacing = 6;
			// Container child hbox29.Gtk.Box+BoxChild
			this.label23 = new global::Gtk.Label();
			this.label23.Name = "label23";
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("Prekoračeno:");
			this.hbox29.Add(this.label23);
			global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.label23]));
			w79.Position = 0;
			w79.Expand = false;
			w79.Fill = false;
			// Container child hbox29.Gtk.Box+BoxChild
			this.labelaPrekoračeno = new global::Gtk.Label();
			this.labelaPrekoračeno.Name = "labelaPrekoračeno";
			this.hbox29.Add(this.labelaPrekoračeno);
			global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.labelaPrekoračeno]));
			w80.Position = 1;
			w80.Expand = false;
			w80.Fill = false;
			this.hbox13.Add(this.hbox29);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.hbox29]));
			w81.Position = 1;
			w81.Expand = false;
			w81.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.hbox30 = new global::Gtk.HBox();
			this.hbox30.Name = "hbox30";
			this.hbox30.Spacing = 6;
			// Container child hbox30.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Budžet:");
			this.hbox30.Add(this.label16);
			global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.label16]));
			w82.Position = 0;
			w82.Expand = false;
			w82.Fill = false;
			// Container child hbox30.Gtk.Box+BoxChild
			this.labelBudzet = new global::Gtk.Label();
			this.labelBudzet.Name = "labelBudzet";
			this.hbox30.Add(this.labelBudzet);
			global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.labelBudzet]));
			w83.Position = 1;
			w83.Expand = false;
			w83.Fill = false;
			this.hbox13.Add(this.hbox30);
			global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.hbox30]));
			w84.Position = 2;
			w84.Fill = false;
			this.table1.Add(this.hbox13);
			global::Gtk.Table.TableChild w85 = ((global::Gtk.Table.TableChild)(this.table1[this.hbox13]));
			w85.TopAttach = ((uint)(4));
			w85.BottomAttach = ((uint)(5));
			w85.XOptions = ((global::Gtk.AttachOptions)(4));
			w85.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox16 = new global::Gtk.HBox();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 115;
			this.hbox16.BorderWidth = ((uint)(6));
			// Container child hbox16.Gtk.Box+BoxChild
			this.hbox27 = new global::Gtk.HBox();
			this.hbox27.Name = "hbox27";
			this.hbox27.Spacing = 6;
			// Container child hbox27.Gtk.Box+BoxChild
			this.label21 = new global::Gtk.Label();
			this.label21.Name = "label21";
			this.label21.Xalign = 0.6F;
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("Kategorija:");
			this.hbox27.Add(this.label21);
			global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.hbox27[this.label21]));
			w86.Position = 0;
			w86.Expand = false;
			w86.Fill = false;
			// Container child hbox27.Gtk.Box+BoxChild
			this.labelaKategorija = new global::Gtk.Label();
			this.labelaKategorija.Name = "labelaKategorija";
			this.hbox27.Add(this.labelaKategorija);
			global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.hbox27[this.labelaKategorija]));
			w87.Position = 1;
			this.hbox16.Add(this.hbox27);
			global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.hbox27]));
			w88.Position = 0;
			w88.Expand = false;
			w88.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.hbox28 = new global::Gtk.HBox();
			this.hbox28.Name = "hbox28";
			this.hbox28.Spacing = 6;
			// Container child hbox28.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("Trošak:");
			this.hbox28.Add(this.label19);
			global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.label19]));
			w89.Position = 0;
			w89.Expand = false;
			w89.Fill = false;
			// Container child hbox28.Gtk.Box+BoxChild
			this.labelaTrosakKategorije = new global::Gtk.Label();
			this.labelaTrosakKategorije.Name = "labelaTrosakKategorije";
			this.hbox28.Add(this.labelaTrosakKategorije);
			global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.labelaTrosakKategorije]));
			w90.Position = 1;
			w90.Expand = false;
			w90.Fill = false;
			this.hbox16.Add(this.hbox28);
			global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.hbox28]));
			w91.Position = 1;
			w91.Fill = false;
			this.table1.Add(this.hbox16);
			global::Gtk.Table.TableChild w92 = ((global::Gtk.Table.TableChild)(this.table1[this.hbox16]));
			w92.TopAttach = ((uint)(2));
			w92.BottomAttach = ((uint)(3));
			w92.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.progressbarBudget = new global::Gtk.ProgressBar();
			this.progressbarBudget.Name = "progressbarBudget";
			this.table1.Add(this.progressbarBudget);
			global::Gtk.Table.TableChild w93 = ((global::Gtk.Table.TableChild)(this.table1[this.progressbarBudget]));
			w93.TopAttach = ((uint)(5));
			w93.BottomAttach = ((uint)(6));
			w93.XOptions = ((global::Gtk.AttachOptions)(4));
			w93.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.progressbarUdio = new global::Gtk.ProgressBar();
			this.progressbarUdio.Name = "progressbarUdio";
			this.progressbarUdio.Text = global::Mono.Unix.Catalog.GetString("Udio kategorije u cjelokupnom trošku");
			this.table1.Add(this.progressbarUdio);
			global::Gtk.Table.TableChild w94 = ((global::Gtk.Table.TableChild)(this.table1[this.progressbarUdio]));
			w94.TopAttach = ((uint)(3));
			w94.BottomAttach = ((uint)(4));
			w94.XOptions = ((global::Gtk.AttachOptions)(4));
			w94.YOptions = ((global::Gtk.AttachOptions)(4));
			this.eventBoxTotalTroskovi.Add(this.table1);
			this.notebook.Add(this.eventBoxTotalTroskovi);
			global::Gtk.Notebook.NotebookChild w96 = ((global::Gtk.Notebook.NotebookChild)(this.notebook[this.eventBoxTotalTroskovi]));
			w96.Position = 2;
			// Notebook tab
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("page4");
			this.notebook.SetTabLabel(this.eventBoxTotalTroskovi, this.label3);
			this.label3.ShowAll();
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.eventBoxStatistika = new global::Gtk.EventBox();
			this.eventBoxStatistika.Name = "eventBoxStatistika";
			// Container child eventBoxStatistika.Gtk.Container+ContainerChild
			this.statMainVBox = new global::Gtk.VBox();
			this.statMainVBox.Name = "statMainVBox";
			this.statMainVBox.Spacing = 6;
			// Container child statMainVBox.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.button11 = new global::Gtk.Button();
			this.button11.CanFocus = true;
			this.button11.Name = "button11";
			this.button11.UseUnderline = true;
			global::Gtk.Image w97 = new global::Gtk.Image();
			w97.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.smallBack.png");
			this.button11.Image = w97;
			this.hbox9.Add(this.button11);
			global::Gtk.Box.BoxChild w98 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.button11]));
			w98.Position = 0;
			w98.Expand = false;
			w98.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.fixed5 = new global::Gtk.Fixed();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			this.hbox9.Add(this.fixed5);
			global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.fixed5]));
			w99.Position = 1;
			// Container child hbox9.Gtk.Box+BoxChild
			this.hbox23 = new global::Gtk.HBox();
			this.hbox23.Name = "hbox23";
			this.hbox23.Spacing = 6;
			// Container child hbox23.Gtk.Box+BoxChild
			this.button12 = new global::Gtk.Button();
			this.button12.CanFocus = true;
			this.button12.Name = "button12";
			this.button12.UseUnderline = true;
			global::Gtk.Image w100 = new global::Gtk.Image();
			w100.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.filterDatum.png");
			this.button12.Image = w100;
			this.hbox23.Add(this.button12);
			global::Gtk.Box.BoxChild w101 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.button12]));
			w101.Position = 0;
			w101.Expand = false;
			w101.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.datumLabela = new global::Gtk.Label();
			this.datumLabela.Name = "datumLabela";
			this.datumLabela.Xalign = 0.1F;
			this.hbox23.Add(this.datumLabela);
			global::Gtk.Box.BoxChild w102 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.datumLabela]));
			w102.Position = 1;
			w102.Expand = false;
			w102.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.hbox25 = new global::Gtk.HBox();
			this.hbox25.Name = "hbox25";
			this.hbox25.Spacing = 6;
			// Container child hbox25.Gtk.Box+BoxChild
			this.fixed10 = new global::Gtk.Fixed();
			this.fixed10.Name = "fixed10";
			this.fixed10.HasWindow = false;
			this.hbox25.Add(this.fixed10);
			global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.fixed10]));
			w103.Position = 0;
			// Container child hbox25.Gtk.Box+BoxChild
			this.button6 = new global::Gtk.Button();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			global::Gtk.Image w104 = new global::Gtk.Image();
			w104.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.openInNewWindow.png");
			this.button6.Image = w104;
			this.hbox25.Add(this.button6);
			global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.button6]));
			w105.Position = 1;
			w105.Expand = false;
			w105.Fill = false;
			this.hbox23.Add(this.hbox25);
			global::Gtk.Box.BoxChild w106 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.hbox25]));
			w106.Position = 2;
			this.hbox9.Add(this.hbox23);
			global::Gtk.Box.BoxChild w107 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.hbox23]));
			w107.Position = 2;
			this.vbox9.Add(this.hbox9);
			global::Gtk.Box.BoxChild w108 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox9]));
			w108.Position = 0;
			w108.Expand = false;
			w108.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Homogeneous = true;
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Kategorije sveukupno:");
			this.hbox10.Add(this.label12);
			global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label12]));
			w109.Position = 0;
			w109.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.hbox21 = new global::Gtk.HBox();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Kategorija:");
			this.hbox21.Add(this.label13);
			global::Gtk.Box.BoxChild w110 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.label13]));
			w110.Position = 0;
			w110.Expand = false;
			w110.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.kategorijeCombo = global::Gtk.ComboBox.NewText();
			this.kategorijeCombo.Name = "kategorijeCombo";
			this.hbox21.Add(this.kategorijeCombo);
			global::Gtk.Box.BoxChild w111 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.kategorijeCombo]));
			w111.Position = 1;
			w111.Expand = false;
			w111.Fill = false;
			this.hbox10.Add(this.hbox21);
			global::Gtk.Box.BoxChild w112 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.hbox21]));
			w112.Position = 1;
			w112.Expand = false;
			w112.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.hbox22 = new global::Gtk.HBox();
			this.hbox22.Name = "hbox22";
			this.hbox22.Spacing = 6;
			// Container child hbox22.Gtk.Box+BoxChild
			this.fixed9 = new global::Gtk.Fixed();
			this.fixed9.Name = "fixed9";
			this.fixed9.HasWindow = false;
			this.hbox22.Add(this.fixed9);
			global::Gtk.Box.BoxChild w113 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.fixed9]));
			w113.Position = 0;
			// Container child hbox22.Gtk.Box+BoxChild
			this.hbox24 = new global::Gtk.HBox();
			this.hbox24.Name = "hbox24";
			this.hbox24.Spacing = 6;
			// Container child hbox24.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Prikaz godine:");
			this.hbox24.Add(this.label14);
			global::Gtk.Box.BoxChild w114 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.label14]));
			w114.Position = 0;
			w114.Expand = false;
			w114.Fill = false;
			// Container child hbox24.Gtk.Box+BoxChild
			this.odabranaGodina = new global::Gtk.SpinButton(0D, 3000D, 1D);
			this.odabranaGodina.CanFocus = true;
			this.odabranaGodina.Name = "odabranaGodina";
			this.odabranaGodina.Adjustment.PageIncrement = 10D;
			this.odabranaGodina.ClimbRate = 1D;
			this.odabranaGodina.Numeric = true;
			this.hbox24.Add(this.odabranaGodina);
			global::Gtk.Box.BoxChild w115 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.odabranaGodina]));
			w115.Position = 1;
			w115.Expand = false;
			w115.Fill = false;
			this.hbox22.Add(this.hbox24);
			global::Gtk.Box.BoxChild w116 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.hbox24]));
			w116.Position = 1;
			w116.Expand = false;
			w116.Fill = false;
			this.hbox10.Add(this.hbox22);
			global::Gtk.Box.BoxChild w117 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.hbox22]));
			w117.Position = 2;
			w117.Fill = false;
			this.vbox9.Add(this.hbox10);
			global::Gtk.Box.BoxChild w118 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox10]));
			w118.Position = 1;
			w118.Expand = false;
			w118.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 55;
			// Container child hbox11.Gtk.Box+BoxChild
			this.hbox18 = new global::Gtk.HBox();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.totalBar = new global::Gtk.Button();
			this.totalBar.CanFocus = true;
			this.totalBar.Name = "totalBar";
			this.totalBar.UseUnderline = true;
			global::Gtk.Image w119 = new global::Gtk.Image();
			this.totalBar.Image = w119;
			this.hbox18.Add(this.totalBar);
			global::Gtk.Box.BoxChild w120 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.totalBar]));
			w120.Position = 0;
			w120.Expand = false;
			w120.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.totalPie = new global::Gtk.Button();
			this.totalPie.CanFocus = true;
			this.totalPie.Name = "totalPie";
			this.totalPie.UseUnderline = true;
			global::Gtk.Image w121 = new global::Gtk.Image();
			this.totalPie.Image = w121;
			this.hbox18.Add(this.totalPie);
			global::Gtk.Box.BoxChild w122 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.totalPie]));
			w122.Position = 1;
			w122.Expand = false;
			w122.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.totalLine = new global::Gtk.Button();
			this.totalLine.CanFocus = true;
			this.totalLine.Name = "totalLine";
			this.totalLine.UseUnderline = true;
			global::Gtk.Image w123 = new global::Gtk.Image();
			this.totalLine.Image = w123;
			this.hbox18.Add(this.totalLine);
			global::Gtk.Box.BoxChild w124 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.totalLine]));
			w124.Position = 2;
			w124.Expand = false;
			w124.Fill = false;
			this.hbox11.Add(this.hbox18);
			global::Gtk.Box.BoxChild w125 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.hbox18]));
			w125.Position = 0;
			w125.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.hbox20 = new global::Gtk.HBox();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.fixed7 = new global::Gtk.Fixed();
			this.fixed7.Name = "fixed7";
			this.fixed7.HasWindow = false;
			this.hbox20.Add(this.fixed7);
			global::Gtk.Box.BoxChild w126 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.fixed7]));
			w126.Position = 0;
			w126.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.kategorijaBar = new global::Gtk.Button();
			this.kategorijaBar.CanFocus = true;
			this.kategorijaBar.Name = "kategorijaBar";
			this.kategorijaBar.UseUnderline = true;
			global::Gtk.Image w127 = new global::Gtk.Image();
			this.kategorijaBar.Image = w127;
			this.hbox20.Add(this.kategorijaBar);
			global::Gtk.Box.BoxChild w128 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.kategorijaBar]));
			w128.Position = 1;
			w128.Expand = false;
			w128.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.kategorijaLine = new global::Gtk.Button();
			this.kategorijaLine.CanFocus = true;
			this.kategorijaLine.Name = "kategorijaLine";
			this.kategorijaLine.UseUnderline = true;
			global::Gtk.Image w129 = new global::Gtk.Image();
			this.kategorijaLine.Image = w129;
			this.hbox20.Add(this.kategorijaLine);
			global::Gtk.Box.BoxChild w130 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.kategorijaLine]));
			w130.Position = 2;
			w130.Expand = false;
			w130.Fill = false;
			this.hbox11.Add(this.hbox20);
			global::Gtk.Box.BoxChild w131 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.hbox20]));
			w131.Position = 1;
			w131.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.fixed8 = new global::Gtk.Fixed();
			this.fixed8.Name = "fixed8";
			this.fixed8.HasWindow = false;
			this.hbox19.Add(this.fixed8);
			global::Gtk.Box.BoxChild w132 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.fixed8]));
			w132.Position = 0;
			// Container child hbox19.Gtk.Box+BoxChild
			this.prikazPoBar = new global::Gtk.Button();
			this.prikazPoBar.CanFocus = true;
			this.prikazPoBar.Name = "prikazPoBar";
			this.prikazPoBar.UseUnderline = true;
			global::Gtk.Image w133 = new global::Gtk.Image();
			this.prikazPoBar.Image = w133;
			this.hbox19.Add(this.prikazPoBar);
			global::Gtk.Box.BoxChild w134 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.prikazPoBar]));
			w134.Position = 1;
			w134.Expand = false;
			w134.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.prikazPoPie = new global::Gtk.Button();
			this.prikazPoPie.CanFocus = true;
			this.prikazPoPie.Name = "prikazPoPie";
			this.prikazPoPie.UseUnderline = true;
			global::Gtk.Image w135 = new global::Gtk.Image();
			this.prikazPoPie.Image = w135;
			this.hbox19.Add(this.prikazPoPie);
			global::Gtk.Box.BoxChild w136 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.prikazPoPie]));
			w136.Position = 2;
			w136.Expand = false;
			w136.Fill = false;
			this.hbox11.Add(this.hbox19);
			global::Gtk.Box.BoxChild w137 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.hbox19]));
			w137.Position = 2;
			w137.Fill = false;
			this.vbox9.Add(this.hbox11);
			global::Gtk.Box.BoxChild w138 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox11]));
			w138.Position = 2;
			w138.Expand = false;
			w138.Fill = false;
			this.statMainVBox.Add(this.vbox9);
			global::Gtk.Box.BoxChild w139 = ((global::Gtk.Box.BoxChild)(this.statMainVBox[this.vbox9]));
			w139.Position = 0;
			w139.Expand = false;
			w139.Fill = false;
			// Container child statMainVBox.Gtk.Box+BoxChild
			this.plotBox = new global::Gtk.VBox();
			this.plotBox.Name = "plotBox";
			this.plotBox.Spacing = 6;
			this.statMainVBox.Add(this.plotBox);
			global::Gtk.Box.BoxChild w140 = ((global::Gtk.Box.BoxChild)(this.statMainVBox[this.plotBox]));
			w140.Position = 1;
			this.eventBoxStatistika.Add(this.statMainVBox);
			this.notebook.Add(this.eventBoxStatistika);
			global::Gtk.Notebook.NotebookChild w142 = ((global::Gtk.Notebook.NotebookChild)(this.notebook[this.eventBoxStatistika]));
			w142.Position = 3;
			// Notebook tab
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("page3");
			this.notebook.SetTabLabel(this.eventBoxStatistika, this.label5);
			this.label5.ShowAll();
			this.Add(this.notebook);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.keyPressEvent);
			this.button2.Clicked += new global::System.EventHandler(this.noviTrosakClicked);
			this.button1.Clicked += new global::System.EventHandler(this.popisClicked);
			this.button3.Clicked += new global::System.EventHandler(this.totalCostClicked);
			this.button4.Clicked += new global::System.EventHandler(this.statistikaClicked);
			this.button5.Clicked += new global::System.EventHandler(this.izlazClicked);
			this.backButton.Clicked += new global::System.EventHandler(this.backButtonClicked);
			this.button7.Clicked += new global::System.EventHandler(this.datumFilterClicked);
			this.button8.Clicked += new global::System.EventHandler(this.brisiSveClicked);
			this.editButton.Clicked += new global::System.EventHandler(this.editTrosakClicked);
			this.backButton1.Clicked += new global::System.EventHandler(this.backButtonClicked);
			this.button9.Clicked += new global::System.EventHandler(this.datumFilterTreeViewClicked);
			this.button10.Clicked += new global::System.EventHandler(this.budgetButtonClicked);
			this.button11.Clicked += new global::System.EventHandler(this.backButtonClicked);
			this.button12.Clicked += new global::System.EventHandler(this.datumFilterClicked);
			this.button6.Clicked += new global::System.EventHandler(this.openInNewWindowClicked);
			this.totalBar.Clicked += new global::System.EventHandler(this.totalClicked);
			this.totalPie.Clicked += new global::System.EventHandler(this.totalClicked);
			this.totalLine.Clicked += new global::System.EventHandler(this.totalClicked);
			this.kategorijaBar.Clicked += new global::System.EventHandler(this.kategorijaGrafClicked);
			this.kategorijaLine.Clicked += new global::System.EventHandler(this.kategorijaGrafClicked);
			this.prikazPoBar.Clicked += new global::System.EventHandler(this.prikazPoGrafClicked);
			this.prikazPoPie.Clicked += new global::System.EventHandler(this.prikazPoGrafClicked);
		}
	}
}
