
// This file has been generated by the GUI designer. Do not modify.
namespace Osobni_Troškovnik
{
	public partial class EditTrosakWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Table table1;

		private global::Gtk.SpinButton cijena;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView opis;

		private global::Gtk.Calendar kalendar;

		private global::Gtk.Label kategorijaLabel;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.Label label4;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button odustani;

		private global::Gtk.Button brisi;

		private global::Gtk.Button spremi;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Osobni_Troškovnik.EditTrosakWindow
			this.Name = "Osobni_Troškovnik.EditTrosakWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Uredi trošak");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.winico.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.BorderWidth = ((uint)(18));
			this.Resizable = false;
			// Container child Osobni_Troškovnik.EditTrosakWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(4)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.cijena = new global::Gtk.SpinButton(0D, 1E+128D, 1D);
			this.cijena.CanFocus = true;
			this.cijena.Name = "cijena";
			this.cijena.Adjustment.PageIncrement = 10D;
			this.cijena.ClimbRate = 1D;
			this.cijena.Digits = ((uint)(2));
			this.cijena.Numeric = true;
			this.table1.Add(this.cijena);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.cijena]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.opis = new global::Gtk.TextView();
			this.opis.CanFocus = true;
			this.opis.Name = "opis";
			this.GtkScrolledWindow.Add(this.opis);
			this.table1.Add(this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.GtkScrolledWindow]));
			w3.TopAttach = ((uint)(3));
			w3.BottomAttach = ((uint)(4));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.kalendar = new global::Gtk.Calendar();
			this.kalendar.CanFocus = true;
			this.kalendar.Name = "kalendar";
			this.kalendar.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.table1.Add(this.kalendar);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.kalendar]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.kategorijaLabel = new global::Gtk.Label();
			this.kategorijaLabel.Name = "kategorijaLabel";
			this.kategorijaLabel.Xalign = 0.03F;
			this.table1.Add(this.kategorijaLabel);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.kategorijaLabel]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Kategorija:");
			this.table1.Add(this.label1);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Cijena:");
			this.table1.Add(this.label2);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.Yalign = 0.03F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Datum:");
			this.table1.Add(this.label3);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.Yalign = 0.04F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Opis:");
			this.table1.Add(this.label4);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.label4]));
			w9.TopAttach = ((uint)(3));
			w9.BottomAttach = ((uint)(4));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add(this.table1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table1]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator1]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 70;
			// Container child hbox1.Gtk.Box+BoxChild
			this.odustani = new global::Gtk.Button();
			this.odustani.CanFocus = true;
			this.odustani.Name = "odustani";
			this.odustani.UseUnderline = true;
			this.odustani.Label = global::Mono.Unix.Catalog.GetString("Odustani");
			this.hbox1.Add(this.odustani);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.odustani]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.brisi = new global::Gtk.Button();
			this.brisi.CanFocus = true;
			this.brisi.Name = "brisi";
			this.brisi.UseUnderline = true;
			this.brisi.Label = global::Mono.Unix.Catalog.GetString("Briši trošak");
			this.hbox1.Add(this.brisi);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.brisi]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.spremi = new global::Gtk.Button();
			this.spremi.CanFocus = true;
			this.spremi.Name = "spremi";
			this.spremi.UseUnderline = true;
			this.spremi.Label = global::Mono.Unix.Catalog.GetString("Spremi");
			this.hbox1.Add(this.spremi);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.spremi]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 377;
			this.DefaultHeight = 409;
			this.Show();
			this.odustani.Clicked += new global::System.EventHandler(this.odustaniClicked);
			this.brisi.Clicked += new global::System.EventHandler(this.brisiClicked);
			this.spremi.Clicked += new global::System.EventHandler(this.spremiClicked);
		}
	}
}
