
// This file has been generated by the GUI designer. Do not modify.
namespace Osobni_Troškovnik
{
	public partial class MainWindow
	{
		private global::Gtk.Notebook notebook;

		private global::Gtk.EventBox eventboxHome;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Image image1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.Button button2;

		private global::Gtk.Button button1;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Fixed fixed4;

		private global::Gtk.Button button3;

		private global::Gtk.Button button4;

		private global::Gtk.Fixed fixed3;

		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Button button5;

		private global::Gtk.Label label1;

		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Button backButton;

		private global::Gtk.Button button7;

		private global::Gtk.Label datumLabel;

		private global::Gtk.HBox hbox4;

		private global::Gtk.ScrolledWindow kategorijeSW;

		private global::Gtk.HBox kategorijeHBox;

		private global::Gtk.VBox vbox6;

		private global::Gtk.HBox hbox5;

		private global::Gtk.ScrolledWindow scrolledwindow2;

		private global::Gtk.NodeView nodeView;

		private global::Gtk.VBox vbox7;

		private global::Gtk.Label info;

		private global::Gtk.HBox hbox6;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView opisView;

		private global::Gtk.Button editButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Osobni_Troškovnik.MainWindow
			this.Name = "Osobni_Troškovnik.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DefaultWidth = 700;
			this.DefaultHeight = 560;
			// Container child Osobni_Troškovnik.MainWindow.Gtk.Container+ContainerChild
			this.notebook = new global::Gtk.Notebook();
			this.notebook.CanFocus = true;
			this.notebook.Name = "notebook";
			this.notebook.CurrentPage = 1;
			this.notebook.ShowBorder = false;
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.eventboxHome = new global::Gtk.EventBox();
			this.eventboxHome.Name = "eventboxHome";
			// Container child eventboxHome.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.image.png");
			this.vbox1.Add(this.image1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.image1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 20;
			this.hbox1.BorderWidth = ((uint)(10));
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.hbox1.Add(this.fixed2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.fixed2]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.dodajTrosak.png");
			this.button2.Image = w3;
			this.hbox1.Add(this.button2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button2]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			global::Gtk.Image w5 = new global::Gtk.Image();
			w5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.popisTroskova.png");
			this.button1.Image = w5;
			this.hbox1.Add(this.button1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button1]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox1.Add(this.fixed1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.fixed1]));
			w7.Position = 3;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 20;
			// Container child hbox2.Gtk.Box+BoxChild
			this.fixed4 = new global::Gtk.Fixed();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			this.hbox2.Add(this.fixed4);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.fixed4]));
			w9.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			global::Gtk.Image w10 = new global::Gtk.Image();
			w10.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.ukupniTroskovi.png");
			this.button3.Image = w10;
			this.hbox2.Add(this.button3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button3]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button4 = new global::Gtk.Button();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			global::Gtk.Image w12 = new global::Gtk.Image();
			w12.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.statistika.png");
			this.button4.Image = w12;
			this.hbox2.Add(this.button4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button4]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			this.hbox2.Add(this.fixed3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.fixed3]));
			w14.Position = 3;
			this.vbox2.Add(this.hbox2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			this.vbox1.Add(this.vbox4);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox4]));
			w17.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button5 = new global::Gtk.Button();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			global::Gtk.Image w18 = new global::Gtk.Image();
			w18.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.izlaz.png");
			this.button5.Image = w18;
			this.hbox3.Add(this.button5);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button5]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w20.Position = 3;
			w20.Expand = false;
			w20.Fill = false;
			this.eventboxHome.Add(this.vbox1);
			this.notebook.Add(this.eventboxHome);
			// Notebook tab
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("page1");
			this.notebook.SetTabLabel(this.eventboxHome, this.label1);
			this.label1.ShowAll();
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.backButton = new global::Gtk.Button();
			this.backButton.WidthRequest = 0;
			this.backButton.HeightRequest = 0;
			this.backButton.CanFocus = true;
			this.backButton.Name = "backButton";
			this.backButton.UseUnderline = true;
			global::Gtk.Image w23 = new global::Gtk.Image();
			w23.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.smallBack.png");
			this.backButton.Image = w23;
			this.hbox7.Add(this.backButton);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.backButton]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.button7 = new global::Gtk.Button();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			global::Gtk.Image w25 = new global::Gtk.Image();
			w25.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.filterDatum.png");
			this.button7.Image = w25;
			this.hbox7.Add(this.button7);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.button7]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.datumLabel = new global::Gtk.Label();
			this.datumLabel.Name = "datumLabel";
			this.hbox7.Add(this.datumLabel);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.datumLabel]));
			w27.Position = 2;
			this.vbox5.Add(this.hbox7);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox7]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 15;
			// Container child hbox4.Gtk.Box+BoxChild
			this.kategorijeSW = new global::Gtk.ScrolledWindow();
			this.kategorijeSW.WidthRequest = 300;
			this.kategorijeSW.CanFocus = true;
			this.kategorijeSW.Name = "kategorijeSW";
			this.kategorijeSW.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child kategorijeSW.Gtk.Container+ContainerChild
			global::Gtk.Viewport w29 = new global::Gtk.Viewport();
			w29.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.kategorijeHBox = new global::Gtk.HBox();
			this.kategorijeHBox.Name = "kategorijeHBox";
			this.kategorijeHBox.Spacing = 6;
			w29.Add(this.kategorijeHBox);
			this.kategorijeSW.Add(w29);
			this.hbox4.Add(this.kategorijeSW);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.kategorijeSW]));
			w32.Position = 0;
			w32.Expand = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			this.nodeView = new global::Gtk.NodeView();
			this.nodeView.CanFocus = true;
			this.nodeView.Name = "nodeView";
			this.scrolledwindow2.Add(this.nodeView);
			this.hbox5.Add(this.scrolledwindow2);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.scrolledwindow2]));
			w34.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.info = new global::Gtk.Label();
			this.info.Name = "info";
			this.vbox7.Add(this.info);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.info]));
			w35.Position = 0;
			w35.Expand = false;
			this.hbox5.Add(this.vbox7);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox7]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			this.vbox6.Add(this.hbox5);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox5]));
			w37.Position = 0;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.opisView = new global::Gtk.TextView();
			this.opisView.CanFocus = true;
			this.opisView.Name = "opisView";
			this.opisView.Editable = false;
			this.GtkScrolledWindow.Add(this.opisView);
			this.hbox6.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.GtkScrolledWindow]));
			w39.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.editButton = new global::Gtk.Button();
			this.editButton.HeightRequest = 50;
			this.editButton.CanFocus = true;
			this.editButton.Name = "editButton";
			this.editButton.UseUnderline = true;
			global::Gtk.Image w40 = new global::Gtk.Image();
			w40.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Osobni_Troškovnik.Pics.edit.png");
			this.editButton.Image = w40;
			this.hbox6.Add(this.editButton);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.editButton]));
			w41.Position = 1;
			w41.Expand = false;
			w41.Fill = false;
			this.vbox6.Add(this.hbox6);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox6]));
			w42.Position = 1;
			w42.Expand = false;
			this.hbox4.Add(this.vbox6);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox6]));
			w43.Position = 1;
			this.vbox5.Add(this.hbox4);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox4]));
			w44.Position = 1;
			this.notebook.Add(this.vbox5);
			global::Gtk.Notebook.NotebookChild w45 = ((global::Gtk.Notebook.NotebookChild)(this.notebook[this.vbox5]));
			w45.Position = 1;
			this.Add(this.notebook);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.keyPressEvent);
			this.button2.Clicked += new global::System.EventHandler(this.noviTrosakClicked);
			this.button1.Clicked += new global::System.EventHandler(this.popisClicked);
			this.button3.Clicked += new global::System.EventHandler(this.totalCostClicked);
			this.button4.Clicked += new global::System.EventHandler(this.statistikaClicked);
			this.button5.Clicked += new global::System.EventHandler(this.izlazClicked);
			this.backButton.Clicked += new global::System.EventHandler(this.backButtonClicked);
			this.button7.Clicked += new global::System.EventHandler(this.datumFilterClicked);
			this.editButton.Clicked += new global::System.EventHandler(this.editTrosakClicked);
		}
	}
}
